apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp_mongo
  labels:
    app: mvp_mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brians-mongo
  template:
    metadata:
      labels:
        app: brians-mongo
    spec:
      containers:
      - name: brians-mongo
        image: mongo:3.6.8
        ports:
        - containerPort: 27017
          protocol: TCP
